export type SubjectData = {
  [chapter: string]: string[];
};

export type ClassData = {
  [subject: string]: string[];
};

export type NCERTData = {
  [cls: string]: ClassData;
};

export const NCERT_CHAPTERS: NCERTData = {
  "Class 1": {
    "Mathematics": [
      "Shapes and Space",
      "Numbers from One to Nine",
      "Addition",
      "Subtraction",
      "Numbers from Ten to Twenty",
      "Time",
      "Measurement",
      "Numbers from Twenty-one to Fifty",
      "Data Handling",
      "Patterns",
      "Numbers",
      "Money",
      "How Many",
    ],
    "English (Marigold)": [
      "A Happy Child / Three Little Pigs",
      "After a Bath / The Bubble, the Straw and the Shoe",
      "One Little Kitten / Lalu and Peelu",
      "Once I Saw a Little Bird / Mittu and the Yellow Mango",
      "Merry-Go-Round / Circle",
      "If I Were an Apple / Our Tree",
      "A Kite / Sundari",
      "A Little Turtle / The Tiger and the Mosquito",
      "Clouds / Anandi's Rainbow",
      "Flying Man / The Tailor and his Friend",
    ],
    "Hindi (Rimjhim)": [
      "झूला",
      "आम की कहानी",
      "आम की टोकरी",
      "पत्ते ही पत्ते",
      "पकौड़ी",
      "छुक-छुक गाड़ी",
      "रसोईघर",
      "चूहो! म्याऊँ सो रही है",
      "बन्दर और गिलहरी",
      "पगड़ी",
      "पतंग",
      "गेंद-बल्ला",
      "बंदर गया खेत में भाग",
      "एक बुढ़िया",
      "मैं भी",
      "लालू और पीलू",
      "चकई के चकदुम",
      "छोटी का कमाल",
      "चाँद वाली अम्मा",
      "बिन बोले बात",
      "हलीम चला चाँद पर",
      "हाथी चल्लम चल्लम",
      "सात पूँछ का चूहा",
    ],
  },

  "Class 2": {
    "Mathematics": [
      "What is Long, What is Round?",
      "Counting in Groups",
      "How Much Can You Carry?",
      "Counting in Tens",
      "Patterns",
      "Footprints",
      "Jugs and Mugs",
      "Tens and Ones",
      "My Funday",
      "Add our Points",
      "Lines and Lines",
      "Give and Take",
      "The Longest Step",
      "Birds Come, Birds Go",
      "How Many Ponytails?",
    ],
    "English (Marigold)": [
      "First Day at School / Bubble",
      "Haldi's Adventure / Rain",
      "I am Lucky / I Want",
      "Our English Class / A Smile",
      "Mr. Nobody / Books",
      "The Wind and the Sun / Clouds",
      "Storm in the Garden / Funny Bunny",
      "The Monkey and the Crocodile / Water",
      "Granny Granny Please Comb my Hair / The Magic Porridge Pot",
      "Strange Talk / The Grasshopper and the Ant",
    ],
    "Hindi (Rimjhim)": [
      "ऊँट चला",
      "भालू ने खेली फुटबॉल",
      "म्याऊँ, म्याऊँ!!",
      "अधिक बलवान कौन?",
      "दोस्त की मदद",
      "बहुत हुआ",
      "मेरी किताब",
      "तितली और कली",
      "बुलबुल",
      "मीठी सारंगी",
      "टेसू राजा बीच बाज़ार",
      "बस के नीचे बाघ",
      "सूरज जल्दी आना जी",
      "नटखट चूहा",
      "एक्की-दोक्की",
    ],
  },

  "Class 3": {
    "Mathematics": [
      "Where to Look From",
      "Fun with Numbers",
      "Give and Take",
      "Long and Short",
      "Shapes and Designs",
      "Fun with Give and Take",
      "Time Goes On",
      "Who is Heavier?",
      "How Many Times",
      "Play with Patterns",
      "Jugs and Mugs",
      "Can We Share?",
      "Smart Charts",
      "Rupees and Paise",
    ],
    "English (Marigold)": [
      "Good Morning / The Magic Garden",
      "Bird Talk / Nina and the Baby Sparrows",
      "Cloud / The Enormous Turnip",
      "The Ship of the Desert / The Camel's Nose",
      "Sea Song / The Giant's Mistake",
      "The Donkey / The Yellow Butterfly",
      "Puppy and I / Little Tiger, Big Tiger",
      "What's in the Mailbox? / My Silly Sister",
      "Don't Tell / He is My Brother",
      "How Creatures Move / The Story of the Road",
    ],
    "Hindi (Rimjhim)": [
      "कक्कू",
      "शेखीबाज़ मक्खी",
      "चाँद वाली अम्मा",
      "मन करता है",
      "बहादुर बित्तो",
      "हमसे सब कहते",
      "टिपटिपवा",
      "बंदर बाँट",
      "अक्ल बड़ी या भैंस",
      "क्योंकि",
      "मीरा बहन और बाघ",
      "जब मुझे साँप ने काटा",
      "मिर्च का मज़ा",
      "सबसे अच्छा पेड़",
    ],
    "Environmental Studies (Looking Around)": [
      "Poonam's Day Out",
      "The Plant Fairy",
      "Water O Water",
      "Our First School",
      "Chhotu's House",
      "Foods We Eat",
      "Saying Without Speaking",
      "Flying High",
      "It's Raining",
      "What is Cooking",
      "From Here to There",
      "Work We Do",
      "Sharing Our Feelings",
      "The Story of Food",
      "Making Pots",
      "Games We Play",
      "Here Comes a Letter",
      "A House Like This",
      "Our Friends - Animals",
      "Drop by Drop",
      "Families Can Be Different",
      "Left Right",
      "A Beautiful Cloth",
      "Web of Life",
    ],
  },

  "Class 4": {
    "Mathematics": [
      "Building with Bricks",
      "Long and Short",
      "A Trip to Bhopal",
      "Tick-Tick-Tick",
      "The Way The World Looks",
      "The Junk Seller",
      "Jugs and Mugs",
      "Carts and Wheels",
      "Halves and Quarters",
      "Play with Patterns",
      "Tables and Shares",
      "How Heavy? How Light?",
      "Fields and Fences",
      "Smart Charts",
    ],
    "English (Marigold)": [
      "Wake Up! / Neha's Alarm Clock",
      "Noses / The Little Fir Tree",
      "Run! / Nasruddin's Aim",
      "Why / Alice in Wonderland",
      "Don't be Afraid of the Dark / Helen Keller",
      "Hiawatha / The Scholar's Mother Tongue",
      "A Watering Rhyme / The Giving Tree",
      "Books / Going to Buy a Book",
      "Pinocchio / The Unfinished Story",
      "In the Garden / Around the World",
    ],
    "Hindi (Rimjhim)": [
      "मन के भोले-भाले बादल",
      "जैसा सवाल वैसा जवाब",
      "किरमिच की गेंद",
      "पापा जब बच्चे थे",
      "दोस्त की पोशाक",
      "नाव बनाओ नाव बनाओ",
      "दान का हिसाब",
      "कौन?",
      "स्वतंत्रता की ओर",
      "थप्प रोटी थप्प दाल",
      "पढ़क्कू की सूझ",
      "सुनीता की पहिया कुर्सी",
      "हुदहुद",
      "मुफ़्त ही मुफ़्त",
    ],
    "Environmental Studies (Looking Around)": [
      "Going to School",
      "Ear to Ear",
      "A Day with Nandu",
      "The Story of Amrita",
      "Anita and the Honeybees",
      "Omana's Journey",
      "From the Window",
      "Reaching Grandmother's House",
      "Changing Families",
      "Hu Tu Tu, Hu Tu Tu",
      "The Valley of Flowers",
      "Changing Times",
      "A River's Tale",
      "Basva's Farm",
      "From Market to Home",
      "A Busy Month",
      "Nandita in Mumbai",
      "Too Much Water, Too Little Water",
      "Abdul in the Garden",
      "Eating Together",
      "Food and Fun",
      "The World in my Home",
      "Pochampalli",
      "Home and Abroad",
    ],
  },

  "Class 5": {
    "Mathematics": [
      "The Fish Tale",
      "Shapes and Angles",
      "How Many Squares?",
      "Parts and Wholes",
      "Does it Look the Same?",
      "Be My Multiple, I'll be Your Factor",
      "Can You See the Pattern?",
      "Mapping Your Way",
      "Boxes and Sketches",
      "Tenths and Hundredths",
      "Area and its Boundary",
      "Smart Charts",
      "Ways to Multiply and Divide",
      "How Big? How Heavy?",
    ],
    "English (Marigold)": [
      "Ice-cream Man / Wonderful Waste!",
      "Teamwork / Flying Together",
      "My Shadow / Robinson Crusoe",
      "Crying / My Elder Brother",
      "The Lazy Frog / Rip Van Winkle",
      "Class Discussion / The Talkative Barber",
      "Topsy-turvy Land / Gulliver's Travels",
      "Nobody's Friend / The Little Bully",
      "Around the World / Sing a Song of People",
      "Who Will be Ningthou? / Malu Bhalu",
    ],
    "Hindi (Rimjhim)": [
      "राख की रस्सी",
      "फ़सलों के त्योहार",
      "खिलौनेवाला",
      "नन्हा फ़नकार",
      "जहाँ चाह वहाँ राह",
      "चिट्ठी का सफ़र",
      "डाकिए की कहानी, कँवरसिंह की ज़ुबानी",
      "वे दिन भी क्या दिन थे",
      "एक माँ की बेबसी",
      "एक दिन की बादशाहत",
      "चावल की रोटियाँ",
      "गुरु और चेला",
      "स्वामी की दादी",
      "बाघ आया उस रात",
      "बिशन की दिलेरी",
      "पानी रे पानी",
      "छोटी-सी हमारी नदी",
      "चुनौती हिमालय की",
    ],
    "Environmental Studies (Looking Around)": [
      "Super Senses",
      "A Snake Charmer's Story",
      "From Tasting to Digesting",
      "Mangoes Round the Year",
      "Seeds and Seeds",
      "Every Drop Counts",
      "Experiments with Water",
      "A Treat for Mosquitoes",
      "Up You Go!",
      "Walls Tell Stories",
      "Sunita in Space",
      "What if it Finishes...?",
      "A Shelter so High!",
      "When the Earth Shook!",
      "Blow Hot, Blow Cold",
      "Who Will Do This Work?",
      "Across the Wall",
      "No Place for Us?",
      "A Seed Tells a Farmer's Story",
      "Whose Forests?",
      "Like Father, Like Daughter",
      "On the Move Again",
    ],
  },

  "Class 6": {
    "Mathematics": [
      "Knowing Our Numbers",
      "Whole Numbers",
      "Playing with Numbers",
      "Basic Geometrical Ideas",
      "Understanding Elementary Shapes",
      "Integers",
      "Fractions",
      "Decimals",
      "Data Handling",
      "Mensuration",
      "Algebra",
      "Ratio and Proportion",
      "Symmetry",
      "Practical Geometry",
    ],
    "Science (Curiosity)": [
      "The Curious Child and the World",
      "Exploring the Animal World",
      "From Grains to Bread",
      "Different Types of Plants and Animals",
      "The Human Body — What's Inside?",
      "Materials in Our Daily Life",
      "Properties of Materials and Water",
      "The Natural World: Our Lifeline",
      "Weather and Water",
      "Beyond the Earth",
      "The Senses and Nervous System",
      "From Seed to Harvest",
      "Adaptation in Different Environments",
      "Air, Water and Climate",
    ],
    "Social Science (Exploring Society — India and Beyond)": [
      "Locating Places on the Earth",
      "The Earth's Structure",
      "Climate of India",
      "Drainage in India",
      "Physical Features of India",
      "When, Where and How: Understanding History",
      "From Gathering to Growing Food",
      "The Earliest Cities",
      "Politics and the Making of Laws",
      "The Government and Its Functions",
      "Our Diverse Languages",
      "Livelihood of People",
      "Trade and Commerce",
    ],
    "English (Honeysuckle)": [
      "Who Did Patrick's Homework?",
      "How the Dog Found Himself a New Master!",
      "Taro's Reward",
      "An Indian – American Woman in Space: Kalpana Chawla",
      "A Different Kind of School",
      "Who I Am",
      "Fair Play",
      "A Game of Chance",
      "Desert Animals",
      "The Banyan Tree",
    ],
    "Hindi (Vasant)": [
      "वह चिड़िया जो",
      "बचपन",
      "नादान दोस्त",
      "चाँद से थोड़ी सी गप्पें",
      "अक्षरों का महत्व",
      "पार नज़र के",
      "साथी हाथ बढ़ाना",
      "ऐसे – ऐसे",
      "टिकट-अलबम",
      "झाँसी की रानी",
      "जो देखकर भी नहीं देखते",
      "संसार पुस्तक है",
      "मैं सबसे छोटी होऊँ",
      "लोकगीत",
      "नौकर",
      "वन के मार्ग में",
      "साँस-साँस में बाँस",
    ],
    "Sanskrit (Ruchira)": [
      "शब्द परिचय: 1",
      "शब्द परिचय: 2",
      "शब्द परिचय: 3",
      "विद्यालय:",
      "वृक्षा:",
      "समुद्रतट:",
      "बकस्य प्रतिशोध:",
      "सूक्तिमौक्तिकम्",
      "क्रीडास्पर्धा",
      "कृषिका:",
      "पुष्पोत्सव:",
      "दशमलव-विभाजनम्",
      "विमानयानं रचयाम",
      "अहह आ: च",
      "मातुलचन्द्र",
    ],
  },

  "Class 7": {
    "Mathematics": [
      "Integers",
      "Fractions and Decimals",
      "Data Handling",
      "Simple Equations",
      "Lines and Angles",
      "The Triangle and its Properties",
      "Congruence of Triangles",
      "Comparing Quantities",
      "Rational Numbers",
      "Practical Geometry",
      "Perimeter and Area",
      "Algebraic Expressions",
      "Exponents and Powers",
      "Symmetry",
      "Visualising Solid Shapes",
    ],
    "Science": [
      "Nutrition in Plants",
      "Nutrition in Animals",
      "Heat",
      "Acids, Bases and Salts",
      "Physical and Chemical Changes",
      "Respiration in Organisms",
      "Transportation in Animals and Plants",
      "Reproduction in Plants",
      "Motion and Time",
      "Electric Current and its Effects",
      "Light",
      "Forests: Our Lifeline",
      "Wastewater Story",
    ],
    "Social Science (History — Our Pasts II)": [
      "Tracing Changes Through a Thousand Years",
      "New Kings and Kingdoms",
      "The Delhi Sultans",
      "The Mughal Empire",
      "Rulers and Buildings",
      "Towns, Traders and Craftspersons",
      "Tribes, Nomads and Settled Communities",
      "Devotional Paths to the Divine",
      "The Making of Regional Cultures",
      "Eighteenth-Century Political Formations",
    ],
    "Social Science (Geography — Our Environment)": [
      "Environment",
      "Inside Our Earth",
      "Our Changing Earth",
      "Air",
      "Water",
      "Natural Vegetation and Wild Life",
      "Human Environment — Settlement, Transport and Communication",
      "Human-Environment Interactions: The Tropical and the Subtropical Region",
      "Life in the Temperate Grasslands",
      "Life in the Deserts",
    ],
    "Social Science (Civics — Social and Political Life II)": [
      "On Equality",
      "Role of the Government in Health",
      "How the State Government Works",
      "Growing Up as Boys and Girls",
      "Women Change the World",
      "Understanding Media",
      "Understanding Advertising",
      "Markets Around Us",
      "A Shirt in the Market",
      "Struggles for Equality",
    ],
    "English (Honeycomb)": [
      "Three Questions",
      "A Gift of Chappals",
      "Gopal and the Hilsa Fish",
      "The Ashes That Made Trees Bloom",
      "Quality",
      "Expert Detectives",
      "The Invention of Vita-Wonk",
      "Fire: Friend and Foe",
      "A Bicycle in Good Repair",
      "The Story of Cricket",
    ],
    "Hindi (Vasant)": [
      "हम पंछी उन्मुक्त गगन के",
      "दादी माँ",
      "हिमालय की बेटियाँ",
      "कठपुतली",
      "मिठाईवाला",
      "रक्त और हमारा शरीर",
      "पापा खो गए",
      "शाम — एक किसान",
      "चिड़िया की बच्ची",
      "अपूर्व अनुभव",
      "रहीम के दोहे",
      "कंचा",
      "एक तिनका",
      "खानपान की बदलती तसवीर",
      "नीलकंठ",
      "भोर और बरखा",
      "वीर कुँवर सिंह",
      "संघर्ष के कारण मैं तुनुकमिज़ाज हो गया",
      "आश्रम का अनुमानित व्यय",
      "विप्लव-गायन",
    ],
    "Sanskrit (Ruchira)": [
      "सुभाषितानि",
      "दुर्बुद्धि: विनश्यति",
      "स्वावलम्बनम्",
      "हास्यबालकविसम्मेलनम्",
      "पण्डिता रमाबाई",
      "सदाचार:",
      "संकल्प: सिद्धिदायक:",
      "त्रिपुरस्य मूर्खा:",
      "अहमपि विद्यालयं गमिष्यामि",
      "विश्वबन्धुत्वम्",
      "समवायो हि दुर्जय:",
      "विद्याधनम्",
      "अमृतं संस्कृतम्",
      "एषा अस्ति स्वर्णभूमि:",
      "लालनगीतम्",
    ],
  },

  "Class 8": {
    "Mathematics": [
      "Rational Numbers",
      "Linear Equations in One Variable",
      "Understanding Quadrilaterals",
      "Practical Geometry",
      "Data Handling",
      "Squares and Square Roots",
      "Cubes and Cube Roots",
      "Comparing Quantities",
      "Algebraic Expressions and Identities",
      "Visualising Solid Shapes",
      "Mensuration",
      "Exponents and Powers",
      "Direct and Inverse Proportions",
      "Factorisation",
      "Introduction to Graphs",
      "Playing with Numbers",
    ],
    "Science": [
      "Crop Production and Management",
      "Microorganisms: Friend and Foe",
      "Coal and Petroleum",
      "Combustion and Flame",
      "Conservation of Plants and Animals",
      "Reproduction in Animals",
      "Reaching the Age of Adolescence",
      "Force and Pressure",
      "Friction",
      "Sound",
      "Chemical Effects of Electric Current",
      "Some Natural Phenomena",
      "Light",
      "Stars and the Solar System",
      "Pollution of Air and Water",
    ],
    "Social Science (History — Our Pasts III)": [
      "How, When and Where",
      "From Trade to Territory: The Company Establishes Power",
      "Ruling the Countryside",
      "Tribals, Dikus and the Vision of a Golden Age",
      "When People Rebel — 1857 and After",
      "Civilising the 'Native', Educating the Nation",
      "Women, Caste and Reform",
      "The Making of the National Movement: 1870s–1947",
      "India After Independence",
    ],
    "Social Science (Geography — Resources and Development)": [
      "Resources",
      "Land, Soil, Water, Natural Vegetation and Wildlife Resources",
      "Mineral and Power Resources",
      "Agriculture",
      "Industries",
      "Human Resources",
    ],
    "Social Science (Civics — Social and Political Life III)": [
      "The Indian Constitution",
      "Understanding Secularism",
      "Why Do We Need a Parliament?",
      "Understanding Laws",
      "Judiciary",
      "Understanding Our Criminal Justice System",
      "Understanding Marginalisation",
      "Confronting Marginalisation",
      "Public Facilities",
      "Law and Social Justice",
    ],
    "English (Honeydew)": [
      "The Best Christmas Present in the World",
      "The Tsunami",
      "Glimpses of the Past",
      "Bepin Choudhury's Lapse of Memory",
      "The Summit Within",
      "This is Jody's Fawn",
      "A Visit to Cambridge",
      "A Short Monsoon Diary",
      "The Great Stone Face I",
      "The Great Stone Face II",
    ],
    "Hindi (Vasant)": [
      "ध्वनि",
      "लाख की चूड़ियाँ",
      "बस की यात्रा",
      "दीवानों की हस्ती",
      "चिट्ठियों की अनूठी दुनिया",
      "भगवान के डाकिए",
      "क्या निराश हुआ जाए",
      "यह सबसे कठिन समय नहीं",
      "कबीर की साखियाँ",
      "कामचोर",
      "जब सिनेमा ने बोलना सीखा",
      "सुदामा चरित",
      "जहाँ पहिया है",
      "अकबरी लोटा",
      "सूरदास के पद",
      "पानी की कहानी",
      "बाज़ और साँप",
      "टोपी",
    ],
    "Sanskrit (Ruchira)": [
      "सुभाषितानि",
      "बिलस्य वाणी न कदापि मे श्रुता",
      "डिजीभारतम्",
      "सदैव पुरतो निधेहि चरणम्",
      "कण्टकेनैव कण्टकम्",
      "गृहं शून्यं सुतां विना",
      "भारतजनताऽहम्",
      "संसारसागरस्य नायका:",
      "सप्तभगिन्य:",
      "नीतिनवनीतम्",
      "सावित्री बाई फुले",
      "कः रक्षति क: रक्षित:",
      "क्षितौ राजते भारतस्वर्णभूमि:",
      "आर्यभटः",
      "प्रहेलिका:",
    ],
  },

  "Class 9": {
    "Mathematics": [
      "Number Systems",
      "Polynomials",
      "Coordinate Geometry",
      "Linear Equations in Two Variables",
      "Introduction to Euclid's Geometry",
      "Lines and Angles",
      "Triangles",
      "Quadrilaterals",
      "Circles",
      "Heron's Formula",
      "Surface Areas and Volumes",
      "Statistics",
    ],
    "Science": [
      "Matter in Our Surroundings",
      "Is Matter Around Us Pure",
      "Atoms and Molecules",
      "Structure of the Atom",
      "The Fundamental Unit of Life",
      "Tissues",
      "Motion",
      "Force and Laws of Motion",
      "Gravitation",
      "Work and Energy",
      "Sound",
      "Improvement in Food Resources",
    ],
    "Social Science (History — India and the Contemporary World I)": [
      "The French Revolution",
      "Socialism in Europe and the Russian Revolution",
      "Nazism and the Rise of Hitler",
      "Forest Society and Colonialism",
      "Pastoralists in the Modern World",
    ],
    "Social Science (Geography — Contemporary India I)": [
      "India — Size and Location",
      "Physical Features of India",
      "Drainage",
      "Climate",
      "Natural Vegetation and Wild Life",
      "Population",
    ],
    "Social Science (Civics — Democratic Politics I)": [
      "What is Democracy? Why Democracy?",
      "Constitutional Design",
      "Electoral Politics",
      "Working of Institutions",
      "Democratic Rights",
    ],
    "Social Science (Economics — Understanding Economic Development I)": [
      "The Story of Village Palampur",
      "People as Resource",
      "Poverty as a Challenge",
      "Food Security in India",
    ],
    "English (Beehive)": [
      "The Fun They Had",
      "The Sound of Music",
      "The Little Girl",
      "A Truly Beautiful Mind",
      "The Snake and the Mirror",
      "My Childhood",
      "Packing",
      "Reach for the Top",
      "The Bond of Love",
      "Kathmandu",
      "If I Were You",
    ],
    "Hindi (Kshitij)": [
      "दो बैलों की कथा",
      "ल्हासा की ओर",
      "उपभोक्तावाद की संस्कृति",
      "साँवले सपनों की याद",
      "नाना साहब की पुत्री देवी मैना को भस्म कर दिया गया",
      "प्रेमचंद के फटे जूते",
      "मेरे बचपन के दिन",
      "एक कुत्ता और एक मैना",
      "साखियाँ एवं सबद",
      "वाख",
      "सवैये",
      "कैदी और कोकिला",
      "ग्राम श्री",
      "चंद्र गहना से लौटती बेर",
      "मेघ आए",
      "यमराज की दिशा",
      "बच्चे काम पर जा रहे हैं",
    ],
  },

  "Class 10": {
    "Mathematics": [
      "Real Numbers",
      "Polynomials",
      "Pair of Linear Equations in Two Variables",
      "Quadratic Equations",
      "Arithmetic Progressions",
      "Triangles",
      "Coordinate Geometry",
      "Introduction to Trigonometry",
      "Some Applications of Trigonometry",
      "Circles",
      "Areas Related to Circles",
      "Surface Areas and Volumes",
      "Statistics",
      "Probability",
    ],
    "Science": [
      "Chemical Reactions and Equations",
      "Acids, Bases and Salts",
      "Metals and Non-Metals",
      "Carbon and its Compounds",
      "Life Processes",
      "Control and Coordination",
      "How do Organisms Reproduce",
      "Heredity",
      "Light — Reflection and Refraction",
      "The Human Eye and the Colourful World",
      "Electricity",
      "Magnetic Effects of Electric Current",
      "Our Environment",
    ],
    "Social Science (History — India and the Contemporary World II)": [
      "The Rise of Nationalism in Europe",
      "Nationalism in India",
      "The Making of a Global World",
      "The Age of Industrialisation",
      "Print Culture and the Modern World",
    ],
    "Social Science (Geography — Contemporary India II)": [
      "Resources and Development",
      "Forest and Wildlife Resources",
      "Water Resources",
      "Agriculture",
      "Minerals and Energy Resources",
      "Manufacturing Industries",
      "Lifelines of National Economy",
    ],
    "Social Science (Civics — Democratic Politics II)": [
      "Power Sharing",
      "Federalism",
      "Gender, Religion and Caste",
      "Political Parties",
      "Outcomes of Democracy",
    ],
    "Social Science (Economics — Understanding Economic Development II)": [
      "Development",
      "Sectors of the Indian Economy",
      "Money and Credit",
      "Globalisation and the Indian Economy",
      "Consumer Rights",
    ],
    "English (First Flight)": [
      "A Letter to God",
      "Nelson Mandela: Long Walk to Freedom",
      "Two Stories about Flying",
      "From the Diary of Anne Frank",
      "The Hundred Dresses I",
      "The Hundred Dresses II",
      "Glimpses of India",
      "Mijbil the Otter",
      "Madam Rides the Bus",
      "The Sermon at Benares",
      "The Proposal",
    ],
    "Hindi (Kshitij)": [
      "सूरदास के पद",
      "राम-लक्ष्मण-परशुराम संवाद",
      "सवैया और कवित्त",
      "आत्मकथ्य",
      "उत्साह और अट नहीं रही है",
      "यह दंतुरित मुस्कान और फसल",
      "छाया मत छूना",
      "कन्यादान",
      "संगतकार",
      "नेताजी का चश्मा",
      "बालगोबिन भगत",
      "लखनवी अंदाज़",
      "मानवीय करुणा की दिव्य चमक",
      "एक कहानी यह भी",
      "स्त्री शिक्षा के विरोधी कुतर्कों का खंडन",
      "नौबतखाने में इबादत",
      "संस्कृति",
    ],
  },

  "Class 11": {
    "Physics": [
      "Physical World",
      "Units and Measurements",
      "Motion in a Straight Line",
      "Motion in a Plane",
      "Laws of Motion",
      "Work, Energy and Power",
      "System of Particles and Rotational Motion",
      "Gravitation",
      "Mechanical Properties of Solids",
      "Mechanical Properties of Fluids",
      "Thermal Properties of Matter",
      "Thermodynamics",
      "Kinetic Theory",
      "Oscillations",
      "Waves",
    ],
    "Chemistry": [
      "Some Basic Concepts of Chemistry",
      "Structure of Atom",
      "Classification of Elements and Periodicity in Properties",
      "Chemical Bonding and Molecular Structure",
      "Thermodynamics",
      "Equilibrium",
      "Redox Reactions",
      "Organic Chemistry: Some Basic Principles and Techniques",
      "Hydrocarbons",
      "Environmental Chemistry (deleted from CBSE 2023–24)",
    ],
    "Biology": [
      "The Living World",
      "Biological Classification",
      "Plant Kingdom",
      "Animal Kingdom",
      "Morphology of Flowering Plants",
      "Anatomy of Flowering Plants",
      "Structural Organisation in Animals",
      "The Unit of Life (Cell: Structure and Function)",
      "Biomolecules",
      "Cell Cycle and Cell Division",
      "Transport in Plants",
      "Mineral Nutrition",
      "Photosynthesis in Higher Plants",
      "Respiration in Plants",
      "Plant Growth and Development",
      "Digestion and Absorption",
      "Breathing and Exchange of Gases",
      "Body Fluids and Circulation",
      "Excretory Products and their Elimination",
      "Locomotion and Movement",
      "Neural Control and Coordination",
      "Chemical Coordination and Integration",
    ],
    "Mathematics": [
      "Sets",
      "Relations and Functions",
      "Trigonometric Functions",
      "Complex Numbers and Quadratic Equations",
      "Linear Inequalities",
      "Permutations and Combinations",
      "Binomial Theorem",
      "Sequences and Series",
      "Straight Lines",
      "Conic Sections",
      "Introduction to Three Dimensional Geometry",
      "Limits and Derivatives",
      "Statistics",
      "Probability",
    ],
    "Economics (Statistics for Economics)": [
      "Introduction",
      "Collection of Data",
      "Organisation of Data",
      "Presentation of Data",
      "Measures of Central Tendency",
      "Measures of Dispersion",
      "Correlation",
      "Index Numbers",
    ],
    "Economics (Indian Economic Development)": [
      "Indian Economy on the Eve of Independence",
      "Indian Economy 1950–1990",
      "Liberalisation, Privatisation and Globalisation: An Appraisal",
      "Poverty",
      "Human Capital Formation in India",
      "Rural Development",
      "Employment: Growth, Informalisation and Other Issues",
      "Infrastructure",
      "Environment and Sustainable Development",
    ],
    "Business Studies": [
      "Business, Trade and Commerce",
      "Forms of Business Organisation",
      "Private, Public and Global Enterprises",
      "Business Services",
      "Emerging Modes of Business",
      "Social Responsibility of Business and Business Ethics",
      "Formation of a Company",
      "Sources of Business Finance",
      "Small Business",
      "Internal Trade",
      "International Business",
    ],
    "Accountancy": [
      "Introduction to Accounting",
      "Theory Base of Accounting",
      "Recording of Transactions — I",
      "Recording of Transactions — II",
      "Bank Reconciliation Statement",
      "Trial Balance and Rectification of Errors",
      "Depreciation, Provisions and Reserves",
      "Bill of Exchange",
      "Financial Statements — I",
      "Financial Statements — II",
      "Accounts from Incomplete Records",
      "Applications of Computers in Accounting",
      "Computerised Accounting System",
    ],
    "Computer Science": [
      "Computer Systems and Organisation",
      "Encoding Schemes and Number System",
      "Emerging Trends",
      "Introduction to Problem Solving",
      "Getting Started with Python",
      "Flow of Control",
      "Functions",
      "Strings",
      "Lists",
      "Tuples and Dictionaries",
      "Societal Impacts",
    ],
    "History (Themes in World History)": [
      "From the Beginning of Time",
      "Early Societies",
      "An Empire Across Three Continents",
      "The Central Islamic Lands",
      "Nomadic Empires",
      "The Three Orders",
      "Changing Cultural Traditions",
      "Confrontation of Cultures",
      "The Industrial Revolution",
      "Displacing Indigenous Peoples",
      "Paths to Modernisation",
    ],
    "Political Science (Political Theory)": [
      "Political Theory: An Introduction",
      "Freedom",
      "Equality",
      "Social Justice",
      "Rights",
      "Citizenship",
      "Nationalism",
      "Secularism",
      "Peace",
      "Development",
    ],
    "Geography (Fundamentals of Physical Geography)": [
      "Geography as a Discipline",
      "The Origin and Evolution of the Earth",
      "Interior of the Earth",
      "Distribution of Oceans and Continents",
      "Minerals and Rocks",
      "Geomorphic Processes",
      "Fluvial Landforms",
      "Arid Landforms",
      "Glacial Landforms",
      "Waves, Currents and Tides",
      "Groundwater and Associated Landforms",
      "World Climate and Climate Change",
      "Water (Oceans)",
      "Movements of Ocean Water",
      "Life on the Earth",
      "Biodiversity and Conservation",
    ],
    "English (Hornbill)": [
      "The Portrait of a Lady",
      "We're Not Afraid to Die... if We Can All Be Together",
      "Discovering Tut: the Saga Continues",
      "The Laburnum Top",
      "The Voice of the Rain",
      "Childhood",
      "The Adventure",
      "Silk Road",
      "Father to Son",
    ],
    "Psychology": [
      "What is Psychology?",
      "Methods of Enquiry in Psychology",
      "The Bases of Human Behaviour",
      "Human Development",
      "Sensory, Attentional and Perceptual Processes",
      "Learning",
      "Human Memory",
      "Thinking",
      "Motivation and Emotion",
    ],
  },

  "Class 12": {
    "Physics": [
      "Electric Charges and Fields",
      "Electrostatic Potential and Capacitance",
      "Current Electricity",
      "Moving Charges and Magnetism",
      "Magnetism and Matter",
      "Electromagnetic Induction",
      "Alternating Current",
      "Electromagnetic Waves",
      "Ray Optics and Optical Instruments",
      "Wave Optics",
      "Dual Nature of Radiation and Matter",
      "Atoms",
      "Nuclei",
      "Semiconductor Electronics: Materials, Devices and Simple Circuits",
    ],
    "Chemistry": [
      "Solutions",
      "Electrochemistry",
      "Chemical Kinetics",
      "The d- and f-Block Elements",
      "Coordination Compounds",
      "Haloalkanes and Haloarenes",
      "Alcohols, Phenols and Ethers",
      "Aldehydes, Ketones and Carboxylic Acids",
      "Amines",
      "Biomolecules",
      "Polymers",
      "Chemistry in Everyday Life",
    ],
    "Biology": [
      "Reproduction in Organisms",
      "Sexual Reproduction in Flowering Plants",
      "Human Reproduction",
      "Reproductive Health",
      "Principles of Inheritance and Variation",
      "Molecular Basis of Inheritance",
      "Evolution",
      "Human Health and Disease",
      "Strategies for Enhancement in Food Production",
      "Microbes in Human Welfare",
      "Biotechnology: Principles and Processes",
      "Biotechnology and its Applications",
      "Organisms and Populations",
      "Ecosystem",
      "Biodiversity and Conservation",
    ],
    "Mathematics": [
      "Relations and Functions",
      "Inverse Trigonometric Functions",
      "Matrices",
      "Determinants",
      "Continuity and Differentiability",
      "Application of Derivatives",
      "Integrals",
      "Application of Integrals",
      "Differential Equations",
      "Vector Algebra",
      "Three Dimensional Geometry",
      "Linear Programming",
      "Probability",
    ],
    "Economics (Macroeconomics)": [
      "Introduction to Macroeconomics",
      "National Income Accounting",
      "Money and Banking",
      "Determination of Income and Employment",
      "Government Budget and the Economy",
      "Open Economy Macroeconomics",
    ],
    "Economics (Introductory Microeconomics)": [
      "Introduction",
      "Theory of Consumer Behaviour",
      "Production and Costs",
      "The Theory of the Firm under Perfect Competition",
      "Market Equilibrium",
      "Non-Competitive Markets",
    ],
    "Business Studies": [
      "Nature and Significance of Management",
      "Principles of Management",
      "Business Environment",
      "Planning",
      "Organising",
      "Staffing",
      "Directing",
      "Controlling",
      "Financial Management",
      "Financial Markets",
      "Marketing Management",
      "Consumer Protection",
    ],
    "Accountancy (Accounting for Not-for-Profit Organisations, Partnership Firms and Companies)": [
      "Accounting for Not-for-Profit Organisations",
      "Accounting for Partnership: Basic Concepts",
      "Reconstitution of a Partnership Firm — Admission of a Partner",
      "Reconstitution of a Partnership Firm — Retirement/Death of a Partner",
      "Dissolution of Partnership Firm",
    ],
    "Accountancy (Company Accounts and Analysis of Financial Statements)": [
      "Accounting for Share Capital",
      "Issue and Redemption of Debentures",
      "Financial Statements of a Company",
      "Analysis of Financial Statements",
      "Accounting Ratios",
      "Cash Flow Statement",
    ],
    "Computer Science": [
      "Python Revision Tour",
      "Functions",
      "File Handling",
      "Data Structures: Stack",
      "Data Structures: Queue",
      "Database Concepts",
      "Structured Query Language (SQL)",
      "Exception Handling in Python",
      "Networking and the Internet",
      "Societal Impacts",
    ],
    "History (Themes in Indian History)": [
      "Bricks, Beads and Bones: The Harappan Civilisation",
      "Kings, Farmers and Towns: Early States and Economies",
      "Kinship, Caste and Class: Early Societies",
      "Thinkers, Beliefs and Buildings: Cultural Developments",
      "Through the Eyes of Travellers: Perceptions of Society",
      "Bhakti-Sufi Traditions: Changes in Religious Beliefs and Devotional Texts",
      "An Imperial Capital: Vijayanagara",
      "Peasants, Zamindars and the State: Agrarian Society and the Mughal Empire",
      "Kings and Chronicles: The Mughal Courts",
      "Colonialism and the Countryside: Exploring Official Archives",
      "Rebels and the Raj: The Revolt of 1857 and its Representations",
      "Colonial Cities: Urbanisation, Planning and Architecture",
      "Mahatma Gandhi and the Nationalist Movement: Civil Disobedience and Beyond",
      "Understanding Partition: Politics, Memories, Experiences",
      "Framing the Constitution: The Beginning of a New Era",
    ],
    "Political Science (Contemporary World Politics)": [
      "The Cold War Era",
      "The End of Bipolarity",
      "US Hegemony in World Politics",
      "Alternative Centres of Power",
      "Contemporary South Asia",
      "International Organisations",
      "Security in the Contemporary World",
      "Environment and Natural Resources",
      "Globalisation",
    ],
    "Political Science (Politics in India Since Independence)": [
      "Challenges of Nation Building",
      "Era of One-Party Dominance",
      "Politics of Planned Development",
      "India's External Relations",
      "Challenges to and Restoration of the Congress System",
      "The Crisis of Democratic Order",
      "Rise of Popular Movements",
      "Regional Aspirations",
      "Recent Developments in Indian Politics",
    ],
    "Geography (India: People and Economy)": [
      "Population: Distribution, Density, Growth and Composition",
      "Migration: Types, Causes and Consequences",
      "Human Development",
      "Human Settlements",
      "Land Resources and Agriculture",
      "Water Resources",
      "Mineral and Energy Resources",
      "Manufacturing Industries",
      "Planning and Sustainable Development in Indian Context",
      "Transport and Communication",
      "International Trade",
      "Geographical Perspective on Selected Issues and Problems",
    ],
    "English (Flamingo)": [
      "The Last Lesson",
      "Lost Spring",
      "Deep Water",
      "The Rattrap",
      "Indigo",
      "Poets and Pancakes",
      "The Interview",
      "Going Places",
      "My Mother at Sixty-six",
      "An Elementary School Classroom in a Slum",
      "Keeping Quiet",
      "A Thing of Beauty",
      "A Roadside Stand",
      "Aunt Jennifer's Tigers",
    ],
    "Physical Education": [
      "Management of Sporting Events",
      "Children and Women in Sports",
      "Yoga",
      "Physical Education and Sports for CWSN",
      "Sports and Nutrition",
      "Test, Measurement and Evaluation",
      "Physiology and Injuries in Sports",
      "Biomechanics and Sports",
      "Psychology and Sports",
      "Training in Sports",
    ],
    "Psychology": [
      "Variations in Psychological Attributes",
      "Self and Personality",
      "Meeting Life Challenges",
      "Psychological Disorders",
      "Therapeutic Approaches",
      "Attitude and Social Cognition",
      "Social Influence and Group Processes",
      "Psychology and Life",
      "Developing Psychological Skills",
    ],
  },
};

export const CLASS_LIST = Object.keys(NCERT_CHAPTERS);

export function getSubjects(cls: string): string[] {
  return Object.keys(NCERT_CHAPTERS[cls] || {});
}

export function getChapters(cls: string, subject: string): string[] {
  return NCERT_CHAPTERS[cls]?.[subject] || [];
}
